<?php

namespace AppBundle\Repository;

/**
 * ContainerMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContainerMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
